# HDBSCAN Clustering for RBD sequences (Omicron only), MSA
---
For a baseline comparison to ESM embedded sequences, we will use multiple sequence alignment, and then use one hot to get a numerical representation. Then use UMAP/tSNE+HDBSCAN just like in the ESM embedded sequence clustering.

In [2]:
version_dir = "rbd_o_msa"
version_prefix = "RBD.O.MSA_one_hot-embedded"

We load in the parquet used for RBD ADO MSA, `RBD.ADO.MSA_one_hot-embedded.parquet`. This contains all of the sequences. Then we just drop everything that is not an Omicron variant.

In [3]:
import os
import pandas as pd

parquet_dir = "/panfs/biopan03/prime_ml/prime/notebooks/clustering/rbd/parquets"

parquet_file = os.path.join(parquet_dir, "rbd_ado_msa", "RBD.ADO.MSA_one_hot-embedded.parquet")
embedded_ado_df = pd.read_parquet(parquet_file, engine='fastparquet')
embedded_o_df = embedded_ado_df[embedded_ado_df["variant"] == "Omicron"]

print(len(embedded_ado_df))
print(len(embedded_o_df))

291539
160016

In [4]:
embedded_o_df

,seq_id,seq,variant,pango lineage,embedding
0,EPI_ISL_16604644,RVQ--PTESIVRFPN-ITNLCP-------------FDEV-FNAT--...,Omicron,DY.1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
1,EPI_ISL_14904955,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.5.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
2,EPI_ISL_14904971,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.5.6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
3,EPI_ISL_14906096,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.5.1.10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
4,EPI_ISL_14906040,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.5.2.9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
...,...,...,...,...,...
291533,EPI_ISL_12083634,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.1.15.1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
291534,EPI_ISL_9835815,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
291536,EPI_ISL_17304059,RVQ--PTESIVRFPN-ITNLCP-------------FHEV-FNAT--...,Omicron,XBB.6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
291537,EPI_ISL_17690414,RVQ--PTESIVRFPN-ITNLCP-------------FDEV-FNAT--...,Omicron,BA.2.9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
291538,EPI_ISL_12523663,RVQ--PTESIVRFPN-ITNLCP-------------FDEV-FNA---...,Omicron,BA.2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."

In [5]:
embedded_o_df.to_parquet(os.path.join(parquet_dir, version_dir, f"{version_prefix}.parquet"), index=False)
display(embedded_o_df)

,seq_id,seq,variant,pango lineage,embedding
0,EPI_ISL_16604644,RVQ--PTESIVRFPN-ITNLCP-------------FDEV-FNAT--...,Omicron,DY.1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
1,EPI_ISL_14904955,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.5.5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
2,EPI_ISL_14904971,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.5.6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
3,EPI_ISL_14906096,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.5.1.10,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
4,EPI_ISL_14906040,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.5.2.9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
...,...,...,...,...,...
291533,EPI_ISL_12083634,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.1.15.1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
291534,EPI_ISL_9835815,RVQ--PTESIVRFPNI-TNLCP-------------FDEVF-NAT--...,Omicron,BA.1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
291536,EPI_ISL_17304059,RVQ--PTESIVRFPN-ITNLCP-------------FHEV-FNAT--...,Omicron,XBB.6,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
291537,EPI_ISL_17690414,RVQ--PTESIVRFPN-ITNLCP-------------FDEV-FNAT--...,Omicron,BA.2.9,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
291538,EPI_ISL_12523663,RVQ--PTESIVRFPN-ITNLCP-------------FDEV-FNA---...,Omicron,BA.2,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."

Parameter sweep.

In [6]:
import os
from sklearn.model_selection import ParameterGrid
import pandas as pd
import numpy as np
from tqdm.auto import tqdm

import cupy as cp
from cuml.manifold import UMAP
from cuml.cluster import HDBSCAN
from cuml.preprocessing import LabelEncoder
from cuml.metrics.cluster import adjusted_rand_score, silhouette_score

def umap_hdbscan_parameter_sweep(parquet_file, embedded_df, n_neighbors_list, min_dist_list, min_samples_list, min_cluster_size_list):
    umap_grid = {
        "n_neighbors": n_neighbors_list,
        "min_dist": min_dist_list,
    }
    umap_param_list = list(ParameterGrid(umap_grid))

    hdbscan_grid = {
        "min_samples": min_samples_list,
        "min_cluster_size": min_cluster_size_list,
    }
    hdbscan_param_list = list(ParameterGrid(hdbscan_grid))

    all_results = []

    # CPU -> GPU
    embedding_matrix = np.vstack(embedded_df["embedding"].values).astype(np.float32)
    X_gpu = cp.asarray(embedding_matrix)
    y_true = LabelEncoder().fit_transform(embedded_df["variant"].values)
    y_true_gpu = cp.asarray(y_true)

    # Parameter Sweep (UMAP)
    for umap_params in tqdm(umap_param_list, desc="UMAP sweep"):
        reducer = UMAP(
            n_neighbors=umap_params["n_neighbors"],
            min_dist=umap_params["min_dist"],
            metric="cosine",
            random_state=42,
        )
        X_red = reducer.fit_transform(X_gpu)
        X_red_cpu = cp.asnumpy(X_red)

        umap_df = pd.DataFrame({
            'UMAP 1': X_red_cpu[:, 0],
            'UMAP 2': X_red_cpu[:, 1],
            'Seq ID': embedded_df['seq_id'].values,
            'Variant': embedded_df['variant'].values,
            'Pango lineage': embedded_df['pango lineage'].values,
        })
        save_as = parquet_file.replace(".parquet", f".umap-nneighbors{umap_params["n_neighbors"]}_mindist{umap_params["min_dist"]}.parquet")
        umap_df.to_parquet(save_as, engine='fastparquet')

        # Parameter Sweep (HDBSCAN)
        for hdbscan_params in tqdm(hdbscan_param_list, leave=False):
            clusterer = HDBSCAN(
                min_samples=hdbscan_params["min_samples"],
                min_cluster_size=hdbscan_params["min_cluster_size"],
            )

            labels = clusterer.fit_predict(X_red)
            ari = float(adjusted_rand_score(y_true_gpu, labels))
            noise_fraction = float(cp.mean(labels == -1))

            non_noise_mask = labels != -1
            valid_cluster_labels = labels[non_noise_mask]
            
            n_non_noise_samples = int(cp.sum(non_noise_mask))
            n_non_noise_clusters = int(cp.unique(valid_cluster_labels).size)

            # silhouette needs at least two clusters AND
            # avoids the case where every non-noise point is its own cluster
            if n_non_noise_clusters > 1 and n_non_noise_samples > n_non_noise_clusters:
                silhouette_avg = float(silhouette_score(X_red[non_noise_mask], valid_cluster_labels,  metric="cosine"))
            else:
                silhouette_avg = np.nan            

            all_results.append({
                "n_neighbors": umap_params["n_neighbors"],
                "min_dist": umap_params["min_dist"],
                "min_samples": hdbscan_params["min_samples"],
                "min_cluster_size": hdbscan_params["min_cluster_size"],
                "ari": ari,
                "noise_fraction": noise_fraction,
                "silhouette": silhouette_avg,
                "n_clusters": n_non_noise_clusters,
            })
            
        # cleanup
        del X_red
        cp._default_memory_pool.free_all_blocks()

    # Final results of both parameter sweeps
    full_results_df = pd.DataFrame(all_results) # All results
    return full_results_df

/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [7]:
%%time

sweep_dir = "/panfs/biopan03/prime_ml/prime/notebooks/clustering/rbd/param_sweeps"
parquet_dir = "/panfs/biopan03/prime_ml/prime/notebooks/clustering/rbd/parquets"

umap_grid = {
    "n_neighbors": [10, 15, 30, 50, 75, 100],
    "min_dist": [0.0, 0.1, 0.15, 0.25, 0.5, 0.75, 1.0],
}

hdbscan_grid = {
    "min_samples": [10, 25, 50, 100, 250, 500, 1000], # cuml HDBSCAN blocks min_samples above 1023
    "min_cluster_size": [50, 100, 250, 500, 1000, 2500, 5000, 10000, 15000, 20000, 22000],
}

parquet_file = os.path.join(parquet_dir, version_dir, f"{version_prefix}.parquet")
embedded_df = pd.read_parquet(parquet_file, engine="fastparquet")

full_results_umap_df = umap_hdbscan_parameter_sweep(
    parquet_file,
    embedded_df, 
    umap_grid["n_neighbors"],
    umap_grid["min_dist"],
    hdbscan_grid["min_samples"],
    hdbscan_grid["min_cluster_size"],
)

full_results_umap_df.to_csv(os.path.join(sweep_dir, version_dir, f"{version_prefix}-umap_hdbscan-parameter_sweep.csv"), index=False)

UMAP sweep: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42/42 [4:02:14<00:00, 346.05s/it]

CPU times: user 3h 46min 47s, sys: 14min 27s, total: 4h 1min 14s
Wall time: 4h 4min 11s

In [8]:
import os
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", message="n_jobs value 1 overridden to 1 by setting random_state")

from sklearn.model_selection import ParameterGrid
import pandas as pd
import numpy as np
from tqdm.auto import tqdm

import cupy as cp
from cuml.manifold import TSNE
from cuml.cluster import HDBSCAN
from cuml.preprocessing import LabelEncoder
from cuml.metrics.cluster import adjusted_rand_score, silhouette_score

def tsne_hdbscan_parameter_sweep(parquet_file, embedded_df, perplexity_list, min_samples_list, min_cluster_size_list):
    hdbscan_grid = {
        "min_samples": min_samples_list,
        "min_cluster_size": min_cluster_size_list,
    }
    hdbscan_param_list = list(ParameterGrid(hdbscan_grid))

    all_results = []

    # CPU -> GPU
    embedding_matrix = np.vstack(embedded_df["embedding"].values).astype(np.float32)
    X_gpu = cp.asarray(embedding_matrix)
    y_true = LabelEncoder().fit_transform(embedded_df["variant"].values)
    y_true_gpu = cp.asarray(y_true)

    n_samples = X_gpu.shape[0]
    early_exaggeration = 24.0 if n_samples > 10000 else 12.0 # Default 12.0
    learning_rate = max(n_samples / early_exaggeration, 200) # Default: 200

    # Parameter Sweep (TSNE)
    for perp in tqdm(perplexity_list, desc="TSNE sweep"):
        save_as = parquet_file.replace(".parquet", f".tsne-perplexity{perp}.parquet")

        if os.path.exists(save_as):
            print(f"Found existing t-SNE file, loading: {save_as}")
            tsne_df = pd.read_parquet(save_as, engine="fastparquet")

            X_red_cpu = tsne_df[["t-SNE component 1", "t-SNE component 2"]].values.astype(np.float32)
            X_red = cp.asarray(X_red_cpu)

        else:
            reducer = TSNE(
                n_components=2,
                perplexity=perp,
                n_neighbors=3 * perp,   # recommended by cuml, caps at 1023
                init="pca",             # like openTSNE
                metric="cosine",
                method="fft",
                random_state=42,
                early_exaggeration=early_exaggeration,
                learning_rate=learning_rate,
                learning_rate_method=None,
            )
            X_red = reducer.fit_transform(X_gpu)
            X_red_cpu = cp.asnumpy(X_red)

            # Save 
            tsne_df = pd.DataFrame({
                't-SNE component 1': X_red_cpu[:, 0],
                't-SNE component 2': X_red_cpu[:, 1],
                'Seq ID': embedded_df['seq_id'].values,
                'Variant': embedded_df['variant'].values,
                'Pango lineage': embedded_df['pango lineage'].values,
            })
            
            tsne_df.to_parquet(save_as, engine='fastparquet')

        # Parameter Sweep (HDBSCAN)
        for hdbscan_params in tqdm(hdbscan_param_list, leave=False):
            clusterer = HDBSCAN(
                min_samples=hdbscan_params["min_samples"],
                min_cluster_size=hdbscan_params["min_cluster_size"],
            )

            labels = clusterer.fit_predict(X_red)
            ari = float(adjusted_rand_score(y_true_gpu, labels))
            noise_fraction = float(cp.mean(labels == -1))

            non_noise_mask = labels != -1
            valid_cluster_labels = labels[non_noise_mask]
            
            n_non_noise_samples = int(cp.sum(non_noise_mask))
            n_non_noise_clusters = int(cp.unique(valid_cluster_labels).size)

            # silhouette needs at least two clusters AND
            # avoids the case where every non-noise point is its own cluster
            if n_non_noise_clusters > 1 and n_non_noise_samples > n_non_noise_clusters:
                silhouette_avg = float(silhouette_score(X_red[non_noise_mask], valid_cluster_labels,  metric="cosine"))
            else:
                silhouette_avg = np.nan                

            all_results.append({
                "perplexity": perp,
                "min_samples": hdbscan_params["min_samples"],
                "min_cluster_size": hdbscan_params["min_cluster_size"],
                "ari": ari,
                "noise_fraction": noise_fraction,
                "silhouette": silhouette_avg,
                "n_clusters": n_non_noise_clusters,
            })
            
        # cleanup
        del X_red
        cp._default_memory_pool.free_all_blocks()

    # Final results of both parameter sweeps
    full_results_df = pd.DataFrame(all_results) # All results
    return full_results_df

In [9]:
%%time

sweep_dir = "/panfs/biopan03/prime_ml/prime/notebooks/clustering/rbd/param_sweeps"
parquet_dir = "/panfs/biopan03/prime_ml/prime/notebooks/clustering/rbd/parquets"

perplexity_list = [30, 50, 100, 250, 500, 600, 650, 700, 750, 800, 900, 1000]

hdbscan_grid = {
    "min_samples": [10, 25, 50, 100, 250, 500, 1000], # cuml HDBSCAN blocks min_samples above 1023
    "min_cluster_size": [50, 100, 250, 500, 1000, 2500, 5000, 10000, 15000, 20000, 22000],
}

parquet_file = os.path.join(parquet_dir, version_dir, f"{version_prefix}.parquet")
embedded_df = pd.read_parquet(parquet_file, engine="fastparquet")

full_results_tsne_df = tsne_hdbscan_parameter_sweep(
    parquet_file,
    embedded_df, 
    perplexity_list,
    hdbscan_grid["min_samples"],
    hdbscan_grid["min_cluster_size"],
)

full_results_tsne_df.to_csv(os.path.join(sweep_dir, version_dir, f"{version_prefix}-tsne_hdbscan-parameter_sweep.csv"), index=False)

TSNE sweep:  17%|██████████████████████████████████████████████████████                                                                                                                                                                                                                                                                              | 2/12 [06:44<33:38, 201.88s/it]

[2026-04-28 07:13:45.872] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...

TSNE sweep:  25%|█████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                                                                                                   | 3/12 [10:13<30:46, 205.15s/it]

[2026-04-28 07:17:14.916] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...

TSNE sweep:  33%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                                                                        | 4/12 [15:14<32:22, 242.76s/it]/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/cuml/internals/outputs.py:424: UserWarning: n_neighbors (1500) should be < 1024, thresholding n_neighbors to 1023
  res = func(*args, **kwargs)

[2026-04-28 07:22:15.349] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...
[2026-04-28 07:22:15.349] [CUML] [warning] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...

TSNE sweep:  42%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                                             | 5/12 [21:26<33:45, 289.34s/it]/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/cuml/internals/outputs.py:424: UserWarning: n_neighbors (1800) should be < 1024, thresholding n_neighbors to 1023
  res = func(*args, **kwargs)

[2026-04-28 07:28:27.258] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...
[2026-04-28 07:28:27.258] [CUML] [warning] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...

TSNE sweep:  50%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                  | 6/12 [27:41<31:50, 318.41s/it]/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/cuml/internals/outputs.py:424: UserWarning: n_neighbors (1950) should be < 1024, thresholding n_neighbors to 1023
  res = func(*args, **kwargs)

[2026-04-28 07:34:42.090] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...
[2026-04-28 07:34:42.090] [CUML] [warning] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...

TSNE sweep:  58%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                       | 7/12 [33:53<27:59, 336.00s/it]/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/cuml/internals/outputs.py:424: UserWarning: n_neighbors (2100) should be < 1024, thresholding n_neighbors to 1023
  res = func(*args, **kwargs)

[2026-04-28 07:40:54.300] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...
[2026-04-28 07:40:54.300] [CUML] [warning] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...

TSNE sweep:  67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                            | 8/12 [40:08<23:14, 348.52s/it]/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/cuml/internals/outputs.py:424: UserWarning: n_neighbors (2250) should be < 1024, thresholding n_neighbors to 1023
  res = func(*args, **kwargs)

[2026-04-28 07:47:09.628] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...
[2026-04-28 07:47:09.628] [CUML] [warning] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...

TSNE sweep:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                 | 9/12 [46:30<17:56, 358.93s/it]/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/cuml/internals/outputs.py:424: UserWarning: n_neighbors (2400) should be < 1024, thresholding n_neighbors to 1023
  res = func(*args, **kwargs)

[2026-04-28 07:53:31.447] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...
[2026-04-28 07:53:31.447] [CUML] [warning] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...

TSNE sweep:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                     | 10/12 [52:49<12:10, 365.09s/it]/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/cuml/internals/outputs.py:424: UserWarning: n_neighbors (2700) should be < 1024, thresholding n_neighbors to 1023
  res = func(*args, **kwargs)

[2026-04-28 07:59:50.321] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...
[2026-04-28 07:59:50.321] [CUML] [warning] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...

TSNE sweep:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 11/12 [59:12<06:10, 370.78s/it]/panfs/biopan03/prime_ml/miniconda3/envs/blackwell_prime/lib/python3.13/site-packages/cuml/internals/outputs.py:424: UserWarning: n_neighbors (3000) should be < 1024, thresholding n_neighbors to 1023
  res = func(*args, **kwargs)

[2026-04-28 08:06:14.008] [CUML] [warning] Perplexity should be within ranges (5, 50). Your results might be a bit strange...
[2026-04-28 08:06:14.008] [CUML] [warning] # of Nearest Neighbors should be at least 3 * perplexity. Your results might be a bit strange...

TSNE sweep: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [1:05:41<00:00, 328.45s/it]

CPU times: user 1h 3min 28s, sys: 5min 10s, total: 1h 8min 39s
Wall time: 1h 9min 20s